[package]
name = "tcp-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.5.0"
etherparse = "0.14.3"
tun-tap = "0.1.4"

[lib]
name = "tcprs"
path = "src/lib.rs"

[[bin]]
name = "tcprs"
path = "src/main.rs"
